### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by dunovank** [noa/iur#1]
Enjoyed the paper. Any eta on when the code will be available?

**Comment by noa** [comment]
@dunovank Thanks for your interest! We're actively working on a TensorFlow 2.0 compatible release, which will be ready by the end of the month. Time allowing we'll also release a PyTorch version, but no ETA on that yet.

**Comment by dunovank** [comment]
@noa thanks for the quick reply. That's good news I'll keep an eye out for the TF2.0 version.

**Comment by noa** [comment]
@dunovank Initial version of the code is up. Let us know if you run into any issues!

**Comment by dunovank** [comment]
Thanks @noa
