### ISSUE TITLE
function never called

### ISSUE THREAD

**Issue by marcusjbishop** [noa/iur#2]
random_episode_from_tfrecord is defined in aid/features.py but never called. However, scripts/fit.py defines sample_random_episode, which is an elaboration of the unused function. The latter *is* called.

**Comment by marcusjbishop** [comment]
Similarly, tfrecord_dataset is never used, but elaborated on in fit.py.
Also, print_tfrecords is not used, although I can imagine it being helpful for debugging.

**Comment by marcusjbishop** [comment]
... although it bears mentioning that the unused versions have better comments and better docstrings!

**Comment by noa** [comment]
@marcusjbishop Removed the unused code!
